
name: Setup NGINX on all nodes

on:
  push:
    branches:
      - main

jobs:
  setup-nginx:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install NGINX on all nodes
        run: |
          set -e

          for ip in 192.168.8.100 192.168.8.101 192.168.8.102; do
            case $ip in
              192.168.8.100) user="master" ;;
              192.168.8.101) user="worker" ;;
              192.168.8.102) user="worker2" ;;
              *) echo "Unknown IP $ip"; exit 1 ;;
            esac

            echo "Installing NGINX on $ip as $user..."

            ssh -tt -o StrictHostKeyChecking=no $user@$ip << EOF
              set -e
              export DEBIAN_FRONTEND=noninteractive

              echo "Connected as: $(whoami)"

              sudo apt update -y
              sudo apt install -y nginx
              sudo systemctl enable --now nginx
              echo "This is GitHub Actions NGINX server" | sudo tee /var/www/html/index.html

              echo "✅ NGINX installed successfully"
EOF
          done