on:
  push:
    branches:
      - main

jobs:
  setup-nginx:
    runs-on: self-hosted  # runs directly on 192.168.8.100

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install NGINX on all local VMs
        run: |
          for ip in 192.168.8.100 192.168.8.101 192.168.8.102; do
            sshpass -p "123" ssh -o StrictHostKeyChecking=no root@$ip "
              apt update &&
              apt install -y nginx &&
              systemctl start nginx &&
              systemctl enable nginx &&
              echo 'This is GitHub Actions NGINX server' > /var/www/html/index.html
            "
          done
