on:
  push:
    branches:
      - main

jobs:
  setup-nginx:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install NGINX on all VMware VMs
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 192.168.8.100,192.168.8.101,192.168.8.102
          username: root
          password: 123
          script: |
            apt update
            apt install -y nginx
            systemctl start nginx
            systemctl enable nginx
            echo "This is GitHub Actions NGINX server" > /var/www/html/index.html
