- name: Install NGINX on all nodes
  run: |
    for ip in 192.168.8.100 192.168.8.101 192.168.8.102; do
      
      case $ip in
        192.168.8.100) user="master" ;;
        192.168.8.101) user="worker" ;;
        192.168.8.102) user="worker2" ;;
      esac

      echo "Installing NGINX on $ip as $user..."

      ssh -tt -o StrictHostKeyChecking=no $user@$ip << 'EOF'
        whoami
        sudo -n true || echo "❌ sudo still requires password"

        export DEBIAN_FRONTEND=noninteractive
        sudo apt update -y
        sudo apt install -y nginx
        sudo systemctl enable --now nginx
        echo "This is GitHub Actions NGINX server" | sudo tee /var/www/html/index.html
      EOF

    done
